import * as H from '../helper-modules/gen-helpers.js';
import * as SH from '../helper-modules/settings-helpers.js';

function processSettings(formObj) {
    let { angular_unit, argument_sign, trig_function_types } = formObj;
    let error_locations = []; // stores a list of input fields where errors occured (same field can appear multiple times)

    // use sine and cosine if nothing was selected
    if (trig_function_types === undefined) trig_function_types = ['sine','cosine'];

    return {
        angular_unit: angular_unit,
        argument_sign: argument_sign,
        trig_function_types: trig_function_types,
        error_locations: error_locations
    };
}

export default function genTrigEx(formObj) {
    const settings = processSettings(formObj);

    const trigFunctions = {
        sine: {
            prompts: [
                '\\sin\\left(0\\right)',
                '\\sin\\left(\\frac{\\pi}{6}\\right)',
                '\\sin\\left(\\frac{\\pi}{4}\\right)',
                '\\sin\\left(\\frac{\\pi}{3}\\right)',
                '\\sin\\left(\\frac{\\pi}{2}\\right)',
                '\\sin\\left(\\frac{2\\pi}{3}\\right)',
                '\\sin\\left(\\frac{3\\pi}{4}\\right)',
                '\\sin\\left(\\frac{5\\pi}{6}\\right)',
                '\\sin\\left(\\pi\\right)',
                '\\sin\\left(\\frac{7\\pi}{6}\\right)',
                '\\sin\\left(\\frac{5\\pi}{4}\\right)',
                '\\sin\\left(\\frac{4\\pi}{3}\\right)',
                '\\sin\\left(\\frac{3\\pi}{2}\\right)',
                '\\sin\\left(\\frac{5\\pi}{3}\\right)',
                '\\sin\\left(\\frac{7\\pi}{4}\\right)',
                '\\sin\\left(\\frac{11\\pi}{6}\\right)',
                '\\sin\\left(2\\pi\\right)',
                '\\sin\\left(0^\\circ\\right)', 
                '\\sin\\left(30^\\circ\\right)', 
                '\\sin\\left(45^\\circ\\right)', 
                '\\sin\\left(60^\\circ\\right)', 
                '\\sin\\left(90^\\circ\\right)', 
                '\\sin\\left(120^\\circ\\right)', 
                '\\sin\\left(135^\\circ\\right)', 
                '\\sin\\left(150^\\circ\\right)', 
                '\\sin\\left(180^\\circ\\right)', 
                '\\sin\\left(210^\\circ\\right)', 
                '\\sin\\left(225^\\circ\\right)', 
                '\\sin\\left(240^\\circ\\right)', 
                '\\sin\\left(270^\\circ\\right)', 
                '\\sin\\left(300^\\circ\\right)', 
                '\\sin\\left(315^\\circ\\right)', 
                '\\sin\\left(330^\\circ\\right)', 
                '\\sin\\left(360^\\circ\\right)', // negatives after here
                '\\sin\\left(-\\frac{\\pi}{6}\\right)',
                '\\sin\\left(-\\frac{\\pi}{4}\\right)',
                '\\sin\\left(-\\frac{\\pi}{3}\\right)',
                '\\sin\\left(-\\frac{\\pi}{2}\\right)',
                '\\sin\\left(-\\frac{2\\pi}{3}\\right)',
                '\\sin\\left(-\\frac{3\\pi}{4}\\right)',
                '\\sin\\left(-\\frac{5\\pi}{6}\\right)',
                '\\sin\\left(-\\pi\\right)',
                '\\sin\\left(-\\frac{7\\pi}{6}\\right)',
                '\\sin\\left(-\\frac{5\\pi}{4}\\right)',
                '\\sin\\left(-\\frac{4\\pi}{3}\\right)',
                '\\sin\\left(-\\frac{3\\pi}{2}\\right)',
                '\\sin\\left(-\\frac{5\\pi}{3}\\right)',
                '\\sin\\left(-\\frac{7\\pi}{4}\\right)',
                '\\sin\\left(-\\frac{11\\pi}{6}\\right)',
                '\\sin\\left(-2\\pi\\right)',
                '\\sin\\left(-30^\\circ\\right)', 
                '\\sin\\left(-45^\\circ\\right)', 
                '\\sin\\left(-60^\\circ\\right)', 
                '\\sin\\left(-90^\\circ\\right)', 
                '\\sin\\left(-120^\\circ\\right)', 
                '\\sin\\left(-135^\\circ\\right)', 
                '\\sin\\left(-150^\\circ\\right)', 
                '\\sin\\left(-180^\\circ\\right)', 
                '\\sin\\left(-210^\\circ\\right)', 
                '\\sin\\left(-225^\\circ\\right)', 
                '\\sin\\left(-240^\\circ\\right)', 
                '\\sin\\left(-270^\\circ\\right)', 
                '\\sin\\left(-300^\\circ\\right)', 
                '\\sin\\left(-315^\\circ\\right)', 
                '\\sin\\left(-330^\\circ\\right)', 
                '\\sin\\left(-360^\\circ\\right)'
            ],
            answers: [
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0',
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', // answers for negatives ((-1) * positive answers)
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0',
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0'
            ]
        },
        cosine: {
            prompts: [
                '\\cos\\left(0\\right)',
                '\\cos\\left(\\frac{\\pi}{6}\\right)',
                '\\cos\\left(\\frac{\\pi}{4}\\right)',
                '\\cos\\left(\\frac{\\pi}{3}\\right)',
                '\\cos\\left(\\frac{\\pi}{2}\\right)',
                '\\cos\\left(\\frac{2\\pi}{3}\\right)',
                '\\cos\\left(\\frac{3\\pi}{4}\\right)',
                '\\cos\\left(\\frac{5\\pi}{6}\\right)',
                '\\cos\\left(\\pi\\right)',
                '\\cos\\left(\\frac{7\\pi}{6}\\right)',
                '\\cos\\left(\\frac{5\\pi}{4}\\right)',
                '\\cos\\left(\\frac{4\\pi}{3}\\right)',
                '\\cos\\left(\\frac{3\\pi}{2}\\right)',
                '\\cos\\left(\\frac{5\\pi}{3}\\right)',
                '\\cos\\left(\\frac{7\\pi}{4}\\right)',
                '\\cos\\left(\\frac{11\\pi}{6}\\right)',
                '\\cos\\left(2\\pi\\right)',
                '\\cos\\left(0^\\circ\\right)', 
                '\\cos\\left(30^\\circ\\right)', 
                '\\cos\\left(45^\\circ\\right)', 
                '\\cos\\left(60^\\circ\\right)', 
                '\\cos\\left(90^\\circ\\right)', 
                '\\cos\\left(120^\\circ\\right)', 
                '\\cos\\left(135^\\circ\\right)', 
                '\\cos\\left(150^\\circ\\right)', 
                '\\cos\\left(180^\\circ\\right)', 
                '\\cos\\left(210^\\circ\\right)', 
                '\\cos\\left(225^\\circ\\right)', 
                '\\cos\\left(240^\\circ\\right)', 
                '\\cos\\left(270^\\circ\\right)', 
                '\\cos\\left(300^\\circ\\right)', 
                '\\cos\\left(315^\\circ\\right)', 
                '\\cos\\left(330^\\circ\\right)', 
                '\\cos\\left(360^\\circ\\right)', // negatives after here
                '\\cos\\left(-\\frac{\\pi}{6}\\right)',
                '\\cos\\left(-\\frac{\\pi}{4}\\right)',
                '\\cos\\left(-\\frac{\\pi}{3}\\right)',
                '\\cos\\left(-\\frac{\\pi}{2}\\right)',
                '\\cos\\left(-\\frac{2\\pi}{3}\\right)',
                '\\cos\\left(-\\frac{3\\pi}{4}\\right)',
                '\\cos\\left(-\\frac{5\\pi}{6}\\right)',
                '\\cos\\left(-\\pi\\right)',
                '\\cos\\left(-\\frac{7\\pi}{6}\\right)',
                '\\cos\\left(-\\frac{5\\pi}{4}\\right)',
                '\\cos\\left(-\\frac{4\\pi}{3}\\right)',
                '\\cos\\left(-\\frac{3\\pi}{2}\\right)',
                '\\cos\\left(-\\frac{5\\pi}{3}\\right)',
                '\\cos\\left(-\\frac{7\\pi}{4}\\right)',
                '\\cos\\left(-\\frac{11\\pi}{6}\\right)',
                '\\cos\\left(-2\\pi\\right)',
                '\\cos\\left(-30^\\circ\\right)', 
                '\\cos\\left(-45^\\circ\\right)', 
                '\\cos\\left(-60^\\circ\\right)', 
                '\\cos\\left(-90^\\circ\\right)', 
                '\\cos\\left(-120^\\circ\\right)', 
                '\\cos\\left(-135^\\circ\\right)', 
                '\\cos\\left(-150^\\circ\\right)', 
                '\\cos\\left(-180^\\circ\\right)', 
                '\\cos\\left(-210^\\circ\\right)', 
                '\\cos\\left(-225^\\circ\\right)', 
                '\\cos\\left(-240^\\circ\\right)', 
                '\\cos\\left(-270^\\circ\\right)', 
                '\\cos\\left(-300^\\circ\\right)', 
                '\\cos\\left(-315^\\circ\\right)', 
                '\\cos\\left(-330^\\circ\\right)', 
                '\\cos\\left(-360^\\circ\\right)' 
            ],
            answers: [
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1',
                '1', 
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1', // answers for negatives (same as positives for cosine)
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1',
                '\\frac{\\sqrt{3}}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{1}{2}', 
                '0', 
                '-\\frac{1}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-1', 
                '-\\frac{\\sqrt{3}}{2}', 
                '-\\frac{\\sqrt{2}}{2}', 
                '-\\frac{1}{2}', 
                '0', 
                '\\frac{1}{2}', 
                '\\frac{\\sqrt{2}}{2}', 
                '\\frac{\\sqrt{3}}{2}', 
                '1',
            ]
        },
        tangent: {
            prompts: [
                '\\tan\\left(0\\right)',
                '\\tan\\left(\\frac{\\pi}{6}\\right)',
                '\\tan\\left(\\frac{\\pi}{4}\\right)',
                '\\tan\\left(\\frac{\\pi}{3}\\right)',
                '\\tan\\left(\\frac{\\pi}{2}\\right)',
                '\\tan\\left(\\frac{2\\pi}{3}\\right)',
                '\\tan\\left(\\frac{3\\pi}{4}\\right)',
                '\\tan\\left(\\frac{5\\pi}{6}\\right)',
                '\\tan\\left(\\pi\\right)',
                '\\tan\\left(\\frac{7\\pi}{6}\\right)',
                '\\tan\\left(\\frac{5\\pi}{4}\\right)',
                '\\tan\\left(\\frac{4\\pi}{3}\\right)',
                '\\tan\\left(\\frac{3\\pi}{2}\\right)',
                '\\tan\\left(\\frac{5\\pi}{3}\\right)',
                '\\tan\\left(\\frac{7\\pi}{4}\\right)',
                '\\tan\\left(\\frac{11\\pi}{6}\\right)',
                '\\tan\\left(2\\pi\\right)',
                '\\tan\\left(0^\\circ\\right)', 
                '\\tan\\left(30^\\circ\\right)', 
                '\\tan\\left(45^\\circ\\right)', 
                '\\tan\\left(60^\\circ\\right)', 
                '\\tan\\left(90^\\circ\\right)', 
                '\\tan\\left(120^\\circ\\right)', 
                '\\tan\\left(135^\\circ\\right)', 
                '\\tan\\left(150^\\circ\\right)', 
                '\\tan\\left(180^\\circ\\right)', 
                '\\tan\\left(210^\\circ\\right)', 
                '\\tan\\left(225^\\circ\\right)', 
                '\\tan\\left(240^\\circ\\right)', 
                '\\tan\\left(270^\\circ\\right)', 
                '\\tan\\left(300^\\circ\\right)', 
                '\\tan\\left(315^\\circ\\right)', 
                '\\tan\\left(330^\\circ\\right)', 
                '\\tan\\left(360^\\circ\\right)', // negatives after here
                '\\tan\\left(-\\frac{\\pi}{6}\\right)',
                '\\tan\\left(-\\frac{\\pi}{4}\\right)',
                '\\tan\\left(-\\frac{\\pi}{3}\\right)',
                '\\tan\\left(-\\frac{\\pi}{2}\\right)',
                '\\tan\\left(-\\frac{2\\pi}{3}\\right)',
                '\\tan\\left(-\\frac{3\\pi}{4}\\right)',
                '\\tan\\left(-\\frac{5\\pi}{6}\\right)',
                '\\tan\\left(-\\pi\\right)',
                '\\tan\\left(-\\frac{7\\pi}{6}\\right)',
                '\\tan\\left(-\\frac{5\\pi}{4}\\right)',
                '\\tan\\left(-\\frac{4\\pi}{3}\\right)',
                '\\tan\\left(-\\frac{3\\pi}{2}\\right)',
                '\\tan\\left(-\\frac{5\\pi}{3}\\right)',
                '\\tan\\left(-\\frac{7\\pi}{4}\\right)',
                '\\tan\\left(-\\frac{11\\pi}{6}\\right)',
                '\\tan\\left(-2\\pi\\right)',
                '\\tan\\left(-30^\\circ\\right)', 
                '\\tan\\left(-45^\\circ\\right)', 
                '\\tan\\left(-60^\\circ\\right)', 
                '\\tan\\left(-90^\\circ\\right)', 
                '\\tan\\left(-120^\\circ\\right)', 
                '\\tan\\left(-135^\\circ\\right)', 
                '\\tan\\left(-150^\\circ\\right)', 
                '\\tan\\left(-180^\\circ\\right)', 
                '\\tan\\left(-210^\\circ\\right)', 
                '\\tan\\left(-225^\\circ\\right)', 
                '\\tan\\left(-240^\\circ\\right)', 
                '\\tan\\left(-270^\\circ\\right)', 
                '\\tan\\left(-300^\\circ\\right)', 
                '\\tan\\left(-315^\\circ\\right)', 
                '\\tan\\left(-330^\\circ\\right)', 
                '\\tan\\left(-360^\\circ\\right)'
            ],
            answers: [
                '0',
                '\\frac{\\sqrt{3}}{3}',
                '1',
                '\\sqrt{3}',
                'undefined',
                '-\\sqrt{3}',
                '-1',
                '-\\frac{\\sqrt{3}}{3}',
                '0',
                '\\frac{\\sqrt{3}}{3}',
                '1',
                '\\sqrt{3}',
                'undefined',
                '-\\sqrt{3}',
                '-1',
                '-\\frac{\\sqrt{3}}{3}',
                '0',
                '0',
                '\\frac{\\sqrt{3}}{3}',
                '1',
                '\\sqrt{3}',
                'undefined',
                '-\\sqrt{3}',
                '-1',
                '-\\frac{\\sqrt{3}}{3}',
                '0',
                '\\frac{\\sqrt{3}}{3}',
                '1',
                '\\sqrt{3}',
                'undefined',
                '-\\sqrt{3}',
                '-1',
                '-\\frac{\\sqrt{3}}{3}',
                '0', // negatives after here ((-1) * positive answers)
                '-\\frac{\\sqrt{3}}{3}',
                '-1',
                '-\\sqrt{3}',
                'undefined',
                '\\sqrt{3}',
                '1',
                '\\frac{\\sqrt{3}}{3}',
                '0',
                '-\\frac{\\sqrt{3}}{3}',
                '-1',
                '-\\sqrt{3}',
                'undefined',
                '\\sqrt{3}',
                '1',
                '\\frac{\\sqrt{3}}{3}',
                '0',
                '-\\frac{\\sqrt{3}}{3}',
                '-1',
                '-\\sqrt{3}',
                'undefined',
                '\\sqrt{3}',
                '1',
                '\\frac{\\sqrt{3}}{3}',
                '0',
                '-\\frac{\\sqrt{3}}{3}',
                '-1',
                '-\\sqrt{3}',
                'undefined',
                '\\sqrt{3}',
                '1',
                '\\frac{\\sqrt{3}}{3}',
                '0',
            ]
        }
    }; // prompts and answers for sine, cosine, and tangent
    
    const currentTrigFunction = H.randFromList(settings.trig_function_types); // pick a trig function -> returns string

    // determine which angular units are used 
    let angleType;
    if (settings.angular_unit === 'radians') angleType = 'radians';
    else if (settings.angular_unit === 'degrees') angleType = 'degrees';
    else if (settings.angular_unit === 'both') angleType = H.randFromList(['radians', 'degrees']);

    // determine which argument sign is used
    let argumentSign;
    if (settings.argument_sign === 'positive') argumentSign = 'positive';
    else if (settings.argument_sign === 'negative') argumentSign = 'negative';
    else if (settings.argument_sign === 'both') argumentSign = H.randFromList(['positive', 'negative']);

    let promptIndex; // the index (in the prompts array) of the prompt that will be used 
    if (angleType === 'radians' && argumentSign === 'positive') promptIndex = H.randInt(0,16);
    else if (angleType === 'radians' && argumentSign === 'negative') promptIndex = H.randInt(34,49);
    else if (angleType === 'degrees' && argumentSign === 'positive') promptIndex = H.randInt(17,33);
    else if (angleType === 'degrees' && argumentSign === 'negative') promptIndex = H.randInt(50,65);

    const selectedPrompt = trigFunctions[currentTrigFunction].prompts[promptIndex];
    const selectedAnswer = trigFunctions[currentTrigFunction].answers[promptIndex]; 

    // ensuring erro locations is present in the return of this fuction (even though it doesn't hold anything at the moment)
    let error_locations = [];
    // if you later add error locations in processing settings for trigEx, you need some logic here (see other gen modules)

    return {
        question: selectedPrompt,
        answer: selectedAnswer,
        settings: settings,
        error_locations: error_locations
    };
} 

export const settings_fields = [
    'angular_unit',
    'argument_sign',
    'trig_function_types'
];

export function get_presets() {
    return {
        angular_unit: 'radians',
        argument_sign: 'positive',
        trig_function_types: ['sine','cosine']
    };
}

export function get_rand_settings() {
    return {
        angular_unit: H.randFromList(['radians','degrees','both']),
        argument_sign: H.randFromList(['positive','negative','both']),
        trig_function_types: H.randFromList([['sine'],['cosine'],['tangent']])
    }; 
}